//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.3.1-b171012.0423
// See <a
// href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2018.07.15 at 05:51:10 PM EDT
//

package com.teasoft.passman.persistence.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModelType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ModelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Records" type="{}RecordsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelType", propOrder = {"records"})
public class ModelType {

    @XmlElement(name = "Records", required = true)
    protected RecordsType records;

    /**
     * Gets the value of the records property.
     *
     * @return possible object is {@link RecordsType }
     */
    public RecordsType getRecords() {
        return this.records;
    }

    /**
     * Sets the value of the records property.
     *
     * @param value allowed object is {@link RecordsType }
     */
    public void setRecords(RecordsType value) {
        this.records = value;
    }

}
