//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.3.1-b171012.0423
// See <a
// href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2018.07.15 at 05:51:10 PM EDT
//

package com.teasoft.passman.persistence.xml.binding;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RecordList" type="{}ModelType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"data"})
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(name = "RecordList", required = true)
    protected ModelType model;

    /**
     * Gets the value of the data property.
     *
     * @return possible object is {@link ModelType }
     */
    public ModelType getModel() {
        return this.model;
    }

    /**
     * Sets the value of the data property.
     *
     * @param value allowed object is {@link ModelType }
     */
    public void setModel(ModelType value) {
        this.model = value;
    }

}
